http://localhost:8081/users


###
POST http://localhost:8081/users HTTP/1.1
Content-Type: : application/json

{
    "name": "Jaaki",
    "surname": "Dup",
    "age": 38    
}
###
GET http://localhost:8081/users/b2f617e2-348a-892f-40f9-c2c1fd1edf89


